# Generated by Django 5.1.4 on 2026-04-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_texte', models.TextField(blank=True)),
                ('valeur_echelle', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='surveys.question')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
            },
        ),
        migrations.CreateModel(
            name='ReponseChoix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponse_choix', to='surveys.choix')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponse_choix', to='responses.reponse')),
            ],
            options={
                'verbose_name': 'Réponse — Choix',
                'verbose_name_plural': 'Réponses — Choix',
                'unique_together': {('reponse', 'choix')},
            },
        ),
        migrations.AddField(
            model_name='reponse',
            name='choix_selectionnes',
            field=models.ManyToManyField(blank=True, related_name='reponses', through='responses.ReponseChoix', to='surveys.choix'),
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField()),
                ('cle_session', models.CharField(max_length=64)),
                ('commence_le', models.DateTimeField(auto_now_add=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('est_complete', models.BooleanField(default=False)),
                ('repondant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumission_set', to=settings.AUTH_USER_MODEL)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumission_set', to='surveys.sondage')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-commence_le'],
            },
        ),
        migrations.AddField(
            model_name='reponse',
            name='soumission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='responses.soumission'),
        ),
    ]
