# Generated by Django 5.1.4 on 2026-04-26 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('echelle', 'Échelle'), ('texte', 'Texte libre')], max_length=20)),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('echelle_min', models.IntegerField(default=1)),
                ('echelle_max', models.IntegerField(default=10)),
                ('libelle_min', models.CharField(blank=True, max_length=100)),
                ('libelle_max', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SectionSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('ordre', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='surveys.question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.sectionsondage'),
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_anonyme', models.BooleanField(default=False)),
                ('est_modele', models.BooleanField(default=False)),
                ('est_archive', models.BooleanField(default=False)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('duree_limite_minutes', models.IntegerField(blank=True, null=True)),
                ('max_reponses', models.IntegerField(blank=True, null=True)),
                ('autoriser_integration', models.BooleanField(default=False)),
                ('mot_de_passe', models.CharField(blank=True, max_length=128)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('archive_le', models.DateTimeField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondage_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sondage',
                'verbose_name_plural': 'Sondages',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='sectionsondage',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.sondage'),
        ),
        migrations.CreateModel(
            name='LienPartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('est_public', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='surveys.sondage')),
            ],
            options={
                'verbose_name': 'Lien de partage',
                'verbose_name_plural': 'Liens de partage',
            },
        ),
    ]
