# Generated by Django 5.1.4 on 2026-04-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='condition_choix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_conditionnelles', to='surveys.choix'),
        ),
        migrations.AddField(
            model_name='sondage',
            name='theme',
            field=models.CharField(choices=[('defaut', 'Défaut (Bleu)'), ('moderne', 'Moderne (Violet)'), ('professionnel', 'Professionnel (Vert)'), ('chaleureux', 'Chaleureux (Orange)')], default='defaut', max_length=20),
        ),
    ]
