# Generated by Django 5.1.4 on 2026-04-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_condition_choix_sondage_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='_etait_actif_avant_archive',
            field=models.BooleanField(default=True),
        ),
    ]
