# Generated by Django 5.1.4 on 2026-04-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_total_soumissions', models.IntegerField(default=0)),
                ('nombre_soumissions_completes', models.IntegerField(default=0)),
                ('taux_completion', models.FloatField(default=0.0)),
                ('duree_moyenne_reponse', models.DurationField(blank=True, null=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('sondage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiquesondage', to='surveys.sondage')),
            ],
            options={
                'verbose_name': 'Statistique sondage',
                'verbose_name_plural': 'Statistiques sondages',
            },
        ),
    ]
